<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Functional TestSuite" duration-ms="25" started-at="2016-06-15T21:59:26Z" finished-at="2016-06-15T21:59:26Z">
    <groups>
    </groups>
    <test name="Basic Tests" duration-ms="25" started-at="2016-06-15T21:59:26Z" finished-at="2016-06-15T21:59:26Z">
      <class name="ex5.Annotation_01">
        <test-method status="PASS" signature="test1()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="test1" duration-ms="1" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="beforeClass" is-config="true" duration-ms="0" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="afterMethod" is-config="true" duration-ms="0" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="test2" duration-ms="2" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at ex5.Annotation_01.test2(Annotation_01.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="afterMethod" is-config="true" duration-ms="0" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:ex5.Annotation_01@7921b0a2]" name="afterClass" is-config="true" duration-ms="0" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- ex5.Annotation_01 -->
      <class name="ex5.LoginTest">
        <test-method status="PASS" signature="loginViaFacebook()[pri:0, instance:ex5.LoginTest@6a024a67]" name="loginViaFacebook" duration-ms="6" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginViaFacebook -->
        <test-method status="PASS" signature="loginviaEmail()[pri:0, instance:ex5.LoginTest@6a024a67]" name="loginviaEmail" duration-ms="0" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginviaEmail -->
        <test-method status="PASS" signature="loginviatwitter()[pri:0, instance:ex5.LoginTest@6a024a67]" name="loginviatwitter" duration-ms="1" started-at="2016-06-15T17:59:26Z" finished-at="2016-06-15T17:59:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginviatwitter -->
      </class> <!-- ex5.LoginTest -->
    </test> <!-- Basic Tests -->
  </suite> <!-- Functional TestSuite -->
</testng-results>
